"""Render a contract as CONTRACTS.md.

The TOML is the source and the checker is the enforcement. This is the third
audience: whoever is reading a pull request and wants to know, in one page,
what this service is allowed to do.

Generated rather than hand-written, so the document and the rule that is
actually enforced cannot disagree.
"""

from __future__ import annotations

from jfastframework.contracts.model import Contract

HEADER = """<!-- Generated by `jfast contracts render`. Edit contracts.toml, not this file. -->

# Contracts — {project}

The rules this service holds itself to. `contracts.toml` is the source;
`jfast contracts check` enforces them in CI.

**If you are an AI agent working here, read this before writing code**, and run
`jfast contracts check` before you call the work done. These are not style
preferences — a violation fails the build.
"""


def render(contract: Contract) -> str:
    out: list[str] = [HEADER.format(project=contract.project)]

    if contract.owns or contract.does_not_own:
        out.append("## Scope\n")
        if contract.owns:
            out.append(f"**Owns:** {contract.owns}\n")
        if contract.does_not_own:
            # The more useful half. Most bad code comes from a service
            # quietly growing into something another service already owns.
            out.append(f"**Does not own:** {contract.does_not_own}\n")

    if contract.provides:
        out.append("## Provides\n")
        out.append("| Interface | Kind | Path | Stability |")
        out.append("| --- | --- | --- | --- |")
        for item in contract.provides:
            out.append(f"| `{item.name}` | {item.kind} | `{item.path or '—'}` | {item.stability} |")
        out.append("")
        out.append(
            "A `stable` interface is a promise. Breaking one means a new "
            "version, not an edit in place.\n"
        )

    if contract.consumes:
        out.append("## Consumes\n")
        out.append("| Interface | Kind | Reached via |")
        out.append("| --- | --- | --- |")
        for item in contract.consumes:
            out.append(f"| `{item.name}` | {item.kind} | `{item.via_env or '—'}` |")
        out.append("")

    if contract.layers:
        out.append("## Layers\n")
        out.append(
            "Imports point inward only. A layer may import the layers listed "
            "for it and nothing else.\n"
        )
        out.append("| Layer | Files | May import | Must never import |")
        out.append("| --- | --- | --- | --- |")
        for layer in contract.layers.values():
            paths = "<br>".join(f"`{p}`" for p in layer.paths) or "—"
            allowed = ", ".join(f"`{n}`" for n in layer.may_import) or "**nothing**"
            forbidden = ", ".join(f"`{p}`" for p in layer.forbid_packages) or "—"
            out.append(f"| `{layer.name}` | {paths} | {allowed} | {forbidden} |")
        out.append("")

    if contract.enforce_placement or contract.module_deps:
        out.append("## Modules\n")
        out.append(
            "Queries through a facade, effects through events, nothing through `shared/`. "
            "A module may import another only through `modules/<other>/public.py`, and only "
            "if `<other>` is listed below. The facade takes the caller's session and an "
            "explicit `tenant_id`, and returns DTOs -- never an ORM entity. No raw SQL "
            "against another module's tables; to react to what another module did, "
            "subscribe to its event.\n"
        )
        if contract.module_deps:
            out.append("| Module | May call |")
            out.append("| --- | --- |")
            for name, deps in sorted(contract.module_deps.items()):
                called = ", ".join(f"`modules/{d}/public.py`" for d in deps) or "nothing"
                out.append(f"| `{name}` | {called} |")
            out.append("")
        else:
            out.append("No module declares a dependency: none may call another.\n")

    if contract.forbid_calls or contract.forbid_imports:
        out.append("## Forbidden\n")
        for rule in contract.forbid_imports:
            packages = ", ".join(f"`{p}`" for p in rule.packages)
            where = ", ".join(f"`{p}`" for p in rule.in_paths) or "anywhere"
            out.append(f"- **import {packages}** in {where} — {rule.why}")
        for call in contract.forbid_calls:
            allowed = ", ".join(f"`{p}`" for p in call.except_in)
            suffix = f" (allowed in {allowed})" if allowed else ""
            out.append(f"- **`{call.pattern}()`**{suffix} — {call.why}")
        out.append("")

    if contract.requirements:
        out.append("## Every module must have\n")
        for requirement in contract.requirements:
            out.append(f"- `{requirement.path}` — {requirement.why}")
        out.append("")

    if contract.invariants:
        out.append("## Invariants\n")
        out.append(
            "Rules the checker cannot verify. They are here so a reviewer — "
            "or an agent — knows to look.\n"
        )
        for invariant in contract.invariants:
            out.append(f"- {invariant}")
        out.append("")

    out.append("## Waivers\n")
    out.append(
        "A violation can be waived inline, and the reason is required:\n\n"
        "```python\n"
        "from sqlalchemy import text  # contracts: allow one-off reporting query, JF-412\n"
        "```\n\n"
        "`jfast contracts waivers` lists every one. A waiver is a decision; "
        "decisions nobody revisits are how a contract stops meaning anything.\n"
    )

    out.append("## Checking\n")
    out.append("```bash\njfast contracts check\njfast contracts show --json\n```\n")

    return "\n".join(out)
