"""Deploy a JFast service as a function: AWS Lambda or Google Cloud Run.

Both targets run the **same** ASGI app the container runs. Nothing is rewritten
for serverless, because a second copy of the app that only exists in the cloud
is a second copy that drifts.

What each target actually is:

* **AWS Lambda** -- a container image, invoked through a Function URL. Mangum
  translates the Lambda event into an ASGI scope. Zip packaging is not offered:
  the dependency set here (pydantic's compiled core, optionally asyncpg) makes
  the 250 MB unzipped limit a recurring surprise, and the image path has none
  of that problem.
* **Google Cloud Run** -- your Dockerfile, deployed with ``gcloud run deploy``.
  "Cloud Functions gen2" *is* Cloud Run; deploying the container directly skips
  the functions-framework shim, which only exists to make a WSGI handler look
  like a container.

Read the generated script before running it. It touches your cloud account and
this is the one place in the framework where a mistake costs money.

**Cold starts are the real trade-off.** A JFast app with the database plugin
opens a connection pool on startup, and Lambda runs startup on every cold
container. For a service that is called constantly, a container behind Caddy is
both cheaper and faster. Functions win for spiky, low-volume, or event-driven
work -- a webhook receiver, a nightly job, an image thumbnailer.
"""

from __future__ import annotations

from dataclasses import dataclass

TARGETS = ("aws", "gcp")

# Lambda's Python base images ship the runtime interface client already.
AWS_BASE_IMAGE = "public.ecr.aws/lambda/python:3.12"


@dataclass
class FunctionConfig:
    name: str
    target: str = "aws"
    region: str = "us-east-1"
    # AWS: the account id, needed to build the ECR repository URI.
    account_id: str = ""
    # GCP: the project id.
    project: str = ""
    memory_mb: int = 512
    timeout_seconds: int = 30
    # Function URLs / Cloud Run services are public unless you say otherwise.
    # Left as a deliberate choice rather than a default, because both clouds
    # make "public" the easy option and the mistake is silent.
    public: bool = False


HANDLER_PY = '''"""AWS Lambda entry point. Generated by `jfast deploy function`.

Mangum adapts the Lambda event to ASGI. The app object is the same one
`uvicorn` serves locally -- there is no serverless-specific application.
"""

from mangum import Mangum

from app.main import app

# lifespan="auto" runs the plugin startup hooks on a cold start, so the
# database pool and the cache client exist before the first request. It also
# means a cold start pays for them. If your function only reaches one
# datastore, disabling the plugins it does not need is the cheapest win
# available here.
handler = Mangum(app, lifespan="auto")
'''


def render_handler() -> str:
    return HANDLER_PY


def render_lambda_dockerfile(config: FunctionConfig) -> str:
    return f"""# Generated by `jfast deploy function --target aws`.
FROM {AWS_BASE_IMAGE}

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt mangum

COPY app ./app
COPY handler.py ./

# module.function, resolved inside /var/task by the runtime interface client.
CMD ["handler.handler"]
"""


def render_aws_script(config: FunctionConfig) -> str:
    """Build, push and update. Idempotent: re-run it to deploy again."""
    repo = f"{config.account_id}.dkr.ecr.{config.region}.amazonaws.com/{config.name}"
    auth = "NONE" if config.public else "AWS_IAM"
    return f"""#!/usr/bin/env bash
# Generated by `jfast deploy function --target aws`. Read before running.
set -euo pipefail

NAME="{config.name}"
REGION="{config.region}"
REPO="{repo}"
TAG="${{1:-$(git rev-parse --short HEAD 2>/dev/null || echo latest)}}"

# The tag defaults to the commit, not to "latest": a moving tag makes it
# impossible to say afterwards which code a given invocation ran.

aws ecr describe-repositories --repository-names "$NAME" --region "$REGION" >/dev/null 2>&1 \\
  || aws ecr create-repository --repository-name "$NAME" --region "$REGION" >/dev/null

aws ecr get-login-password --region "$REGION" \\
  | docker login --username AWS --password-stdin "${{REPO%%/*}}"

# Lambda runs x86_64 unless the function is configured for arm64. Building on
# an Apple Silicon or ARM machine without this produces an image that fails at
# invocation with an exec format error, which the console reports as a timeout.
docker build --platform linux/amd64 -t "$REPO:$TAG" .
docker push "$REPO:$TAG"

if aws lambda get-function --function-name "$NAME" --region "$REGION" >/dev/null 2>&1; then
  aws lambda update-function-code \\
    --function-name "$NAME" --image-uri "$REPO:$TAG" --region "$REGION" >/dev/null
  aws lambda wait function-updated --function-name "$NAME" --region "$REGION"
else
  echo "Function $NAME does not exist yet."
  echo "Create it once, with an execution role you control:"
  echo
  echo "  aws lambda create-function --function-name $NAME \\\\"
  echo "    --package-type Image --code ImageUri=$REPO:$TAG \\\\"
  echo "    --role arn:aws:iam::{config.account_id or "<ACCOUNT_ID>"}:role/<EXECUTION_ROLE> \\\\"
  echo "    --memory-size {config.memory_mb} --timeout {config.timeout_seconds} --region $REGION"
  echo
  echo "Then a Function URL:"
  echo "  aws lambda create-function-url-config --function-name $NAME \\\\"
  echo "    --auth-type {auth} --region $REGION"
  exit 1
fi

aws lambda update-function-configuration \\
  --function-name "$NAME" \\
  --memory-size {config.memory_mb} \\
  --timeout {config.timeout_seconds} \\
  --region "$REGION" >/dev/null

echo "Deployed $NAME from $REPO:$TAG"
"""


def render_gcp_script(config: FunctionConfig) -> str:
    ingress = "--allow-unauthenticated" if config.public else "--no-allow-unauthenticated"
    return f"""#!/usr/bin/env bash
# Generated by `jfast deploy function --target gcp`. Read before running.
set -euo pipefail

NAME="{config.name}"
REGION="{config.region}"
PROJECT="{config.project or "<PROJECT_ID>"}"

# --source . builds with Cloud Build using the Dockerfile in this directory,
# so the deployed image is the same one `docker build` produces locally.
#
# "Cloud Functions gen2" is Cloud Run underneath. Deploying to Cloud Run
# directly skips the functions-framework shim, whose only job is making a WSGI
# handler look like a container -- which an ASGI app already is.
gcloud run deploy "$NAME" \\
  --source . \\
  --project "$PROJECT" \\
  --region "$REGION" \\
  --memory {config.memory_mb}Mi \\
  --timeout {config.timeout_seconds}s \\
  {ingress} \\
  --port 8000 \\
  --set-env-vars JFAST_ENV=prod

echo "Deployed $NAME to Cloud Run in $REGION"
"""


def render(config: FunctionConfig) -> dict[str, str]:
    """Every file this target needs, keyed by path relative to the service."""
    if config.target not in TARGETS:
        raise ValueError(f"unknown target {config.target!r}; choose from {', '.join(TARGETS)}")

    if config.target == "aws":
        if not config.account_id:
            # The ECR URI cannot be built without it, and a script with a
            # placeholder in the registry host fails only after the build.
            raise ValueError("the aws target needs --account-id (12 digits)")
        return {
            "handler.py": render_handler(),
            "Dockerfile.lambda": render_lambda_dockerfile(config),
            "deploy-lambda.sh": render_aws_script(config),
        }

    if not config.project:
        raise ValueError("the gcp target needs --project")
    return {"deploy-cloudrun.sh": render_gcp_script(config)}
