#!/usr/bin/env bash
# The upgrade path from the previous release, as a user walks it.
#
#   1. a virtualenv with the previous release from PyPI (PREVIOUS, default the
#      release before this checkout's version)
#   2. a project generated by it: modules in every layout, plugins auth,
#      tenancy, metrics, rag and queue
#   3. this checkout's wheel installed over it
#   4. `jfast upgrade --check --json`, whose change codes must be exactly the
#      ones in scripts/smoke_upgrade.expected
#   5. the remedy for each code, applied by this script as the docs describe it
#   6. the app imported and GET /health answered in-process
#   7. the project's own pytest, and `jfast check --ci`
#
# The claim this keeps honest is the one `jfast upgrade --check` makes: that it
# names everything a project needs to change. A break it does not name shows
# up at step 6 or 7 with nothing at step 4.
#
#   PY=python3.12 scripts/smoke_upgrade.sh
#   PREVIOUS=0.1.0a10 scripts/smoke_upgrade.sh
set -uo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
PY=${PY:-python3}
EXPECTED=${EXPECTED:-${ROOT}/scripts/smoke_upgrade.expected}
WORK=$(mktemp -d)
KEEP=${KEEP_WORK:-}
EXTRAS="server,db,cache,metrics,auth,rag,dev"
rc=0

cleanup() {
  saved=$?
  if [ -n "${KEEP}" ]; then echo "kept ${WORK}"; else rm -rf "${WORK}"; fi
  exit "${saved}"
}
trap cleanup EXIT

fail() {
  echo "FAIL: $*"
  rc=1
}

current=$("${PY}" -c "import re,pathlib; print(re.search(r'__version__ = \"([^\"]+)\"', pathlib.Path('${ROOT}/src/jfastframework/__init__.py').read_text()).group(1))")
if [ -z "${PREVIOUS:-}" ]; then
  # 0.1.0a11 -> 0.1.0a10. Only the alpha series is numbered like this so far;
  # anything else must be given explicitly rather than guessed.
  PREVIOUS=$("${PY}" -c "
import re, sys
m = re.fullmatch(r'(\d+\.\d+\.\d+a)(\d+)', '${current}')
sys.exit('set PREVIOUS: no rule for ${current}') if not m or m[2] == '0' else print(f'{m[1]}{int(m[2]) - 1}')
") || exit 2
fi
echo "### ${PREVIOUS} -> ${current} (this checkout)"

venv="${WORK}/venv"
"${PY}" -m venv "${venv}"
vpy="${venv}/bin/python"
"${vpy}" -m pip install -q --upgrade pip > /dev/null
echo "  installing jfastframework[${EXTRAS}]==${PREVIOUS} from PyPI"
"${vpy}" -m pip install -q "jfastframework[${EXTRAS}]==${PREVIOUS}" || { echo "cannot install ${PREVIOUS}"; exit 2; }

echo "  generating with ${PREVIOUS}"
mkdir -p "${WORK}/project" && cd "${WORK}/project"
"${venv}/bin/jfast" new service shop --with database,auth,tenancy,metrics,rag,queue > gen.log 2>&1 \
  || { cat gen.log; exit 1; }
cd shop
for layout in modular screaming hexagonal layered; do
  "${venv}/bin/jfast" new module "m_${layout}" --layout "${layout}" > /dev/null \
    || fail "${PREVIOUS}: new module --layout ${layout}"
done

echo "  installing this checkout's wheel"
"${vpy}" -m pip wheel -q --no-deps -w "${WORK}/wheels" "${ROOT}" > /dev/null
wheel=$(ls "${WORK}"/wheels/jfastframework-*.whl | head -1)
"${vpy}" -m pip install -q "${wheel}[${EXTRAS}]" || { echo "cannot install ${wheel}"; exit 2; }

echo "  jfast upgrade --check --json"
"${venv}/bin/jfast" upgrade --check --json > upgrade.json
found=$("${vpy}" -c "import json; print('\n'.join(sorted(c['code'] for c in json.load(open('upgrade.json'))['changes'])))")
expected=$(grep -v '^[[:space:]]*#' "${EXPECTED}" | sed '/^[[:space:]]*$/d' | sort)
if [ "${found}" != "${expected}" ]; then
  echo "  expected:"; echo "${expected}" | sed 's/^/    /'
  echo "  reported:"; echo "${found}" | sed 's/^/    /'
  fail "upgrade --check reported a different set of changes than ${EXPECTED##*/}"
fi

# The remedies, as the docs give them. One case per code; a code with no
# remedy here is a code this smoke cannot carry a project through.
remedy() {
  case "$1" in
    hexagonal-eager-create-payload)
      # Defer the CreatePayload import the way 0.1.0a11's template does, so the
      # package init stops importing FastAPI for anyone who imports the domain.
      "${vpy}" - <<'PYEOF'
import re
from pathlib import Path

for init in Path("modules").glob("*/__init__.py"):
    source = init.read_text(encoding="utf-8")
    eager = re.search(
        r"\n(?:#[^\n]*\n)*from \.adapters\.http import (\w+) as CreatePayload\n", source
    )
    if not eager:
        continue
    create = eager.group(1)
    source = source.replace(eager.group(0), "\n")
    source = source.replace(
        '    if name == "router":',
        f'    if name == "CreatePayload":\n        from .adapters.http import {create}\n\n'
        f'        return {create}\n    if name == "router":',
    )
    init.write_text(source, encoding="utf-8")
    print(f"    deferred CreatePayload in {init}")
PYEOF
      ;;
    facade-tenant-optional)
      # tenant_id: str on every facade of a multitenant service, as the note
      # says; the project's own mypy and tests then run on the result.
      "${vpy}" - <<'PYEOF'
import re
from pathlib import Path

for facade in Path("modules").glob("*/public.py"):
    source = facade.read_text(encoding="utf-8")
    fixed = re.sub(r"tenant_id: str \| None(?: = None)?", "tenant_id: str", source)
    if fixed != source:
        facade.write_text(fixed, encoding="utf-8")
        print(f"    tenant_id: str in {facade}")
PYEOF
      ;;
    jfast-env-wins-over-the-file)
      # The note's remedy: drop [app] env (local is the default); the
      # deployment sets JFAST_ENV.
      "${vpy}" - <<'PYEOF'
import re
from pathlib import Path

path = Path("jfast.toml")
source = path.read_text(encoding="utf-8")
fixed = re.sub(r'(?m)^env = "local"\n', "", source, count=1)
if fixed != source:
    path.write_text(fixed, encoding="utf-8")
    print("    removed [app] env from jfast.toml")
PYEOF
      ;;
    unsigned-tenant-needs-a-session)
      # The generated routes use current_tenant and the generated tests sign
      # in: the note needs nothing from this project. Its pytest below is the
      # proof that nothing leaned on an anonymous subdomain tenant.
      echo "    nothing to change: every generated route asks current_tenant"
      ;;
    *)
      fail "no scripted remedy for ${1}: add one to smoke_upgrade.sh as docs/upgrading.md gives it"
      ;;
  esac
}
for code in ${found}; do
  echo "  remedy: ${code}"
  remedy "${code}"
done

echo "  GET /health in-process"
cp .env.example .env
"${vpy}" - <<'PYEOF' || fail "the upgraded app does not boot or /health is not 200"
import asyncio

import httpx

from main import app


async def probe() -> None:
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://smoke") as client:
        response = await client.get("/health")
        assert response.status_code == 200, response.text
        print(f"    /health {response.status_code} {response.json()['status']}")


asyncio.run(probe())
PYEOF

echo "  pytest"
"${vpy}" -m pytest -q -p no:cacheprovider || fail "the upgraded project's own tests"
echo "  jfast check --ci"
"${venv}/bin/jfast" check --ci > check.log 2>&1 || { cat check.log; fail "jfast check --ci"; }

if [ "${rc}" -eq 0 ]; then
  echo "OK: ${PREVIOUS} -> ${current}: upgrade --check named every change, and the project boots and passes"
fi
exit "${rc}"
