"""`jfast migration check` and `jfast migration plan`.

A migration is the one edit that is applied exactly once, to the one copy of
the data that matters, usually by a deploy pipeline nobody is watching. The
failure modes are known and small in number -- it is rejected outright, it
holds a lock long enough to look like an outage, or it succeeds and the data is
wrong afterwards -- and every one of them is visible in the revision's source
before it runs. So this reads them.

**It never imports a revision.** A revision imports the project's models, and
the environment the CLI runs in is not the environment those imports resolve
in: a checker that only works when the project already imports is a checker
that is unavailable in the moment it is needed. Everything below comes out of
`ast`.

Relationship to the generated `migrations/env.py`: that file's
`process_revision_directives` hook repairs a scalar-default `NOT NULL` column
*at generation time*, so revisions autogenerated by a current service should
never trip `migration-add-not-null`. This command is the other half -- it reads
revisions that already exist, including hand-written ones, ones merged from a
branch, and ones generated before that hook existed. The two agree on what is
wrong; they disagree only about when there is still time to fix it.

Every check is decidable from the source text, and the ones that are not are
deliberately absent. A checker that is right nine times in ten is muted after
the second false positive, and the true findings go with it.

`op.execute` is the exception that proves it. Arbitrary SQL cannot be judged
without a SQL parser, so a named list of statement forms is read and everything
else is reported as **unread** rather than passed: `migration-raw-sql` at `low`.
A tick on a statement nobody looked at claims a review that did not happen, and
that is the failure this module exists to prevent.
"""

from __future__ import annotations

import ast
import asyncio
import configparser
import contextlib
import json as jsonlib
import os
import re
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Annotated, Any

import typer

from jfastframework.cli import ui
from jfastframework.cli.exits import Code
from jfastframework.project import SEVERITY_ORDER, Finding
from jfastframework.sql import safe_identifier

__all__ = [
    "Operation",
    "RevisionReport",
    "Risk",
    "RowCounts",
    "analyze_revision",
    "load_revisions",
    "order_revisions",
    "parse_revision",
    "parse_revision_source",
    "python_remedies",
    "register",
    "render_check",
    "render_plan",
    "versions_dir",
]

SCHEMA_VERSION = "1"

#: Operations worth reading. Anything else in a revision is either free
#: (`create_table` on a table that does not exist yet) or not decidable here.

_OPERATIONS = frozenset(
    {
        "add_column",
        "alter_column",
        "create_index",
        "create_table",
        "drop_column",
        "drop_constraint",
        "drop_index",
        "drop_table",
        "execute",
    }
)

#: Receivers an operation can hang off. The batch alias is discovered per
#: `with` block; `op` is the module-level one every revision imports.
_ROOT_RECEIVER = "op"

# `sa.String(50)` -> `sa.String(200)` is a catalogue edit on PostgreSQL, not a
# rewrite. It is also the single most common harmless alteration there is, so
# recognising it is what keeps the type-change finding believable.
_VARCHAR = re.compile(
    r"^(?:sa\.|sqlalchemy\.|postgresql\.)?(?:String|VARCHAR|Unicode)\s*"
    r"\(\s*(?:length\s*=\s*)?(\d*)\s*\)$",
    re.IGNORECASE,
)

# A conversion to a zone-aware timestamp, written by hand in SQL. The `USING`
# clause is looked for in the text between this clause and the next one, so the
# multi-column form is judged per column.
_SQL_TO_TIMESTAMPTZ = re.compile(
    r"alter\s+column\s+(?P<column>[\w\"]+)\s+type\s+"
    r"(?:timestamptz|timestamp\s*(?:\(\d+\))?\s*with\s+time\s+zone)",
    re.IGNORECASE,
)
_SQL_ALTER_COLUMN = re.compile(r"alter\s+column\s", re.IGNORECASE)

# The whole of what `op.execute` is read for. A statement matching none of
# these is reported as unread; the list is short on purpose, because each entry
# is a form whose risk the leading keywords settle without knowing the rest.
_SQL_ALTER_TABLE = re.compile(
    r"\balter\s+table\s+(?:if\s+exists\s+)?(?P<table>[\w.\"]+)", re.IGNORECASE
)
_SQL_ALTER_COLUMN_NAME = re.compile(r"\balter\s+column\s+(?P<column>[\w\"]+)", re.IGNORECASE)
_SQL_DROP_TABLE = re.compile(
    r"\bdrop\s+table\s+(?:if\s+exists\s+)?(?P<table>[\w.\"]+)", re.IGNORECASE
)
_SQL_TRUNCATE = re.compile(r"\btruncate\s+(?:table\s+)?(?P<table>[\w.\"]+)", re.IGNORECASE)
_SQL_DROP_COLUMN = re.compile(
    r"\bdrop\s+column\s+(?:if\s+exists\s+)?(?P<column>[\w\"]+)", re.IGNORECASE
)
_SQL_SET_NOT_NULL = re.compile(r"\bset\s+not\s+null\b", re.IGNORECASE)
_SQL_CREATE_INDEX = re.compile(
    r"\bcreate\s+(?:unique\s+)?index\s+(?P<concurrently>concurrently\s+)?"
    r"(?:if\s+not\s+exists\s+)?(?:(?P<name>[\w\"]+)\s+)?on\s+(?P<table>[\w.\"]+)",
    re.IGNORECASE,
)
_SQL_COLUMN_TYPE = re.compile(
    r"\balter\s+column\s+(?P<column>[\w\"]+)\s+type\s+(?P<type>[\w.]+(?:\s*\([^)]*\))?)",
    re.IGNORECASE,
)

# A statement that copies one column into another. Narrow deliberately: this is
# the evidence that turns a drop-plus-add from data loss into a rename, and a
# loose match here silences a finding that was right.
_SQL_COPIES_INTO = r"\bset\b.*?\b{target}\b\s*="
_SQL_INSERTS_FROM = r"\binsert\s+into\b.*?\b{target}\b.*?\bselect\b"

# Backticked Python inside a step. Every remedy this module writes is a call on
# Alembic's `op`, and the SQL and shell fragments in the same sentences are
# neither valid Python nor meant to be -- so the marker is what the snippet is,
# not the punctuation around it.
_PYTHON_REMEDY = re.compile(r"`((?:with\s+)?op\.[^`]+)`")

# Said in more than one place, so it is written in one. A raw `ALTER TABLE` and
# an `op.alter_column` that do the same thing have to explain it the same way.
_WHY_DROP_TABLE = (
    "Every row is lost and `downgrade` recreates the table empty at best. There is no version "
    "of this that is reversible without a backup taken beforehand."
)
_WHY_DROP_COLUMN = (
    "The column and everything in it are gone, and `downgrade` cannot bring the values back -- "
    "only the empty column. Anything still reading it starts failing at the same instant, "
    "including the copy of the service that has not been replaced yet."
)
_WHY_INDEX_LOCK = (
    "A plain CREATE INDEX blocks every write to the table until it finishes, which on a large "
    "table is minutes and reads as an outage. `postgresql_concurrently=True` avoids it, but the "
    "statement cannot run inside a transaction, so the revision also needs an "
    "`op.get_context().autocommit_block()`."
)
_WHY_SET_NOT_NULL = (
    "SET NOT NULL scans the entire table to prove no row violates it, holding an ACCESS "
    "EXCLUSIVE lock throughout, and aborts on the first NULL it finds. A CHECK constraint added "
    "NOT VALID and validated separately takes only a SHARE UPDATE EXCLUSIVE lock; from "
    "PostgreSQL 12 the SET NOT NULL then skips the scan entirely."
)
_WHY_TYPE_CHANGE = (
    "A type change rewrites the whole table under an ACCESS EXCLUSIVE lock: no reads, no writes, "
    "for as long as the rewrite takes. It also fails partway through on the first row the cast "
    "cannot handle, having already held the lock for that long."
)
_WHY_TIMESTAMPTZ = (
    "This does not fail. It converts through the implicit cast, which reads every stored value "
    "in the *server's* TimeZone, so on any server not set to UTC the whole column silently "
    "shifts and nothing complains. The USING clause is what states the stored values were UTC: "
    "`USING <column> AT TIME ZONE 'UTC'`."
)


# ---------------------------------------------------------------------------
# What a revision says
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Operation:
    """One `op.*` call, reduced to the parts a risk depends on."""

    name: str
    line: int
    table: str | None = None
    column: str | None = None
    #: The index or constraint the call names, which is not a column.
    target: str | None = None
    #: Keyword arguments as written. Values are source text, not objects: a
    #: type is `sa.Numeric(12, 2)` and there is nothing to evaluate it with.
    keywords: Mapping[str, str] = field(default_factory=dict)
    #: The type being moved *to*, from `type_=` or the column's own argument.
    type_text: str | None = None
    #: The literal handed to `op.execute`, when it was a literal.
    sql: str | None = None


@dataclass(frozen=True)
class Revision:
    """One file under `versions/`."""

    path: str
    revision: str
    down_revision: str | None
    message: str
    operations: tuple[Operation, ...]
    downgrade_is_empty: bool
    #: Where `downgrade` is declared, so a finding about it points at it.
    downgrade_line: int = 1

    def tables(self) -> frozenset[str]:
        return frozenset(op.table for op in self.operations if op.table)


@dataclass(frozen=True)
class RowCounts:
    """How full each table is, and whether that is actually known.

    `known=False` is not a synonym for empty and must never be treated as one.
    The whole point of the row count is the difference between "this will be
    rejected" and "this applied fine on the laptop it was written on".
    """

    known: bool
    counts: Mapping[str, int] = field(default_factory=dict)

    #: `counts[table]` when the server said there are rows but would only be
    #: exact after a table scan. Reported as "has rows".
    SOME = -1

    @classmethod
    def unknown(cls) -> RowCounts:
        return cls(known=False)

    def phrase(self, table: str) -> str:
        """How to finish the sentence "widgets ..."."""
        if not self.known:
            return "has an unknown row count, treat as populated"
        if table not in self.counts:
            return "does not exist on this database yet"
        count = self.counts[table]
        if count == 0:
            return "is empty on this database"
        if count == self.SOME:
            return "has rows"
        return "has 1 row" if count == 1 else f"has {count} rows"


@dataclass(frozen=True)
class Risk:
    """A finding, plus the two things `plan` needs that a finding does not carry.

    The finding is `jfastframework.project.Finding` unchanged: severity, code,
    message and why mean here exactly what they mean in `jfast analyze`, and
    render through the same code.
    """

    finding: Finding
    reason: str
    steps: tuple[str, ...]


@dataclass(frozen=True)
class RevisionReport:
    revision: Revision
    risks: tuple[Risk, ...]

    def describe(self) -> dict[str, Any]:
        return {
            "revision": self.revision.revision,
            "path": self.revision.path,
            "message": self.revision.message,
            "findings": [risk.finding.describe() for risk in self.risks],
            "reasons": [risk.reason for risk in self.risks],
        }


# ---------------------------------------------------------------------------
# Reading a revision
# ---------------------------------------------------------------------------


def _string(node: ast.expr | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    # Autogenerate names every index and constraint `op.f("ix_widgets_slug")`,
    # which marks the name as already-final rather than changing it. The
    # argument is the literal, so reading through the wrapper is what makes a
    # generated revision name its own index instead of reporting `None`.
    if isinstance(node, ast.Call) and len(node.args) == 1:
        func = node.func
        if isinstance(func, ast.Attribute) and func.attr == "f":
            return _string(node.args[0])
    return None


def _sql_literal(node: ast.expr | None) -> str | None:
    """The SQL `op.execute` was handed, when the source says what it is.

    `op.execute(sa.text("..."))` is the form autogenerate and most hand-written
    data migrations use, so reading only the bare string leaves the common case
    unread. An f-string or a variable stays None: the statement does not exist
    yet, and there is nothing honest to say about it.
    """
    literal = _string(node)
    if literal is not None:
        return literal
    if isinstance(node, ast.Call) and len(node.args) == 1:
        func = node.func
        named = func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", None)
        if named == "text":
            return _string(node.args[0])
    return None


def _positional(call: ast.Call, index: int) -> ast.expr | None:
    return call.args[index] if len(call.args) > index else None


def _keywords(call: ast.Call) -> dict[str, str]:
    return {kw.arg: ast.unparse(kw.value) for kw in call.keywords if kw.arg is not None}


def _keyword_string(call: ast.Call, name: str) -> str | None:
    """A keyword argument's *value*, not its source text.

    `_keywords` unparses, which is right for a type but wrong for a name:
    `table_name="widgets"` comes back as `'widgets'`, quote characters and all,
    and a table spelled that way matches nothing on the database.
    """
    for keyword in call.keywords:
        if keyword.arg == name:
            return _string(keyword.value)
    return None


def _attr_name(node: ast.expr) -> tuple[str, str] | None:
    """`(receiver, method)` for `receiver.method(...)`, else None."""
    if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
        return None
    if not isinstance(node.func.value, ast.Name):
        return None
    return node.func.value.id, node.func.attr


def _assigned(node: ast.stmt) -> tuple[list[ast.expr], ast.expr | None]:
    """`(targets, value)` for either assignment form, `([], None)` for anything else.

    `script.py.mako` writes `revision: str = "..."`, so the annotated form is
    the one this framework's own revisions arrive in; a parser that reads only
    `ast.Assign` reads none of them.
    """
    if isinstance(node, ast.Assign):
        return list(node.targets), node.value
    if isinstance(node, ast.AnnAssign):
        # `revision: str` with no value is legal and carries nothing.
        return [node.target], node.value
    return [], None


def _module_string(tree: ast.Module, name: str) -> str | None:
    """A top-level `name = "..."` assignment, which is how Alembic stamps ids."""
    for node in tree.body:
        targets, value = _assigned(node)
        if value is None:
            continue
        for target in targets:
            if isinstance(target, ast.Name) and target.id == name:
                literal = _string(value)
                if literal is not None:
                    return literal
                # A merge revision writes `down_revision = ("a", "b")`. The
                # first parent is enough to order the chain.
                if isinstance(value, ast.Tuple | ast.List) and value.elts:
                    return _string(value.elts[0])
    return None


def _function(tree: ast.Module, name: str) -> ast.FunctionDef | None:
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return node
    return None


def _is_empty(func: ast.FunctionDef | None) -> bool:
    """A body that is a docstring, `pass` or `...` and nothing else."""
    if func is None:
        return True
    for statement in func.body:
        if isinstance(statement, ast.Pass):
            continue
        if isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Constant):
            continue
        return False
    return True


def _column_call(node: ast.expr | None) -> ast.Call | None:
    """The `sa.Column(...)` (or bare `Column(...)`) an `add_column` was handed."""
    if not isinstance(node, ast.Call):
        return None
    if isinstance(node.func, ast.Attribute) and node.func.attr == "Column":
        return node
    if isinstance(node.func, ast.Name) and node.func.id == "Column":
        return node
    return None


def _operation(call: ast.Call, batch_table: str | None) -> Operation | None:
    named = _attr_name(call)
    if named is None:
        return None
    _, method = named
    if method not in _OPERATIONS:
        return None

    line = call.lineno
    keywords = _keywords(call)

    if method == "execute":
        return Operation(name=method, line=line, sql=_sql_literal(_positional(call, 0)))

    if method in {"create_table", "drop_table"}:
        table = batch_table or _string(_positional(call, 0))
        return Operation(name=method, line=line, table=table, keywords=keywords)

    if method == "add_column":
        # Batch mode drops the table argument; it is on the `with` instead.
        column_node = _positional(call, 0 if batch_table else 1)
        table = batch_table or _string(_positional(call, 0))
        declared = _column_call(column_node)
        if declared is None:
            return Operation(name=method, line=line, table=table, keywords=keywords)
        # The column's own keywords are the ones that decide this: `nullable`
        # and `server_default` live on `sa.Column`, not on `op.add_column`.
        merged = {**keywords, **_keywords(declared)}
        return Operation(
            name=method,
            line=line,
            table=table,
            column=_string(_positional(declared, 0)),
            keywords=merged,
            type_text=(
                ast.unparse(declared.args[1]) if len(declared.args) > 1 else merged.get("type_")
            ),
        )

    if method == "drop_column":
        table = batch_table or _string(_positional(call, 0))
        column = _string(_positional(call, 0 if batch_table else 1))
        return Operation(name=method, line=line, table=table, column=column, keywords=keywords)

    if method == "alter_column":
        table = batch_table or _string(_positional(call, 0))
        column = _string(_positional(call, 0 if batch_table else 1))
        return Operation(
            name=method,
            line=line,
            table=table,
            column=column,
            keywords=keywords,
            type_text=keywords.get("type_"),
        )

    if method in {"create_index", "drop_index", "drop_constraint"}:
        target = _string(_positional(call, 0))
        table = batch_table or _string(_positional(call, 1)) or _keyword_string(call, "table_name")
        return Operation(name=method, line=line, table=table, target=target, keywords=keywords)

    return Operation(name=method, line=line, table=batch_table, keywords=keywords)


def _expressions(node: ast.stmt) -> Iterator[ast.expr]:
    """Expressions directly under *node*, skipping the bodies it may contain."""
    for child in ast.iter_child_nodes(node):
        if isinstance(child, ast.expr):
            yield child


def _scan(body: Sequence[ast.stmt], batch: tuple[str, str] | None, found: list[Operation]) -> None:
    """Collect operations, carrying the table a batch block binds.

    Written as a descent rather than `ast.walk` for one reason: inside
    `with op.batch_alter_table("widgets") as batch_op:` the operations no
    longer name their table, and a flat walk has nowhere to put that fact.
    """
    for node in body:
        if isinstance(node, ast.With | ast.AsyncWith):
            nested = batch
            for item in node.items:
                named = _attr_name(item.context_expr)
                if named is None or named[1] != "batch_alter_table":
                    continue
                assert isinstance(item.context_expr, ast.Call)
                table = _string(_positional(item.context_expr, 0))
                alias = item.optional_vars
                if table is not None and isinstance(alias, ast.Name):
                    nested = (alias.id, table)
            _scan(node.body, nested, found)
            continue

        for expression in _expressions(node):
            for sub in ast.walk(expression):
                if not isinstance(sub, ast.Call):
                    continue
                named = _attr_name(sub)
                if named is None:
                    continue
                receiver, _ = named
                if receiver == _ROOT_RECEIVER:
                    operation = _operation(sub, None)
                elif batch is not None and receiver == batch[0]:
                    operation = _operation(sub, batch[1])
                else:
                    continue
                if operation is not None:
                    found.append(operation)

        for attribute in ("body", "orelse", "finalbody"):
            nested_body = getattr(node, attribute, None)
            if isinstance(nested_body, list):
                _scan([n for n in nested_body if isinstance(n, ast.stmt)], batch, found)
        for handler in getattr(node, "handlers", []):
            _scan(handler.body, batch, found)


def parse_revision_source(source: str, *, path: str) -> Revision:
    """Read one revision from its text. Never imports it."""
    tree = ast.parse(source)
    upgrade = _function(tree, "upgrade")
    operations: list[Operation] = []
    if upgrade is not None:
        _scan(upgrade.body, None, operations)

    identifier = _module_string(tree, "revision") or Path(path).stem
    docstring = ast.get_docstring(tree) or ""
    downgrade = _function(tree, "downgrade")
    return Revision(
        path=path,
        revision=identifier,
        down_revision=_module_string(tree, "down_revision"),
        message=docstring.splitlines()[0].strip() if docstring else "",
        operations=tuple(operations),
        downgrade_is_empty=_is_empty(downgrade),
        downgrade_line=downgrade.lineno if downgrade is not None else 1,
    )


def parse_revision(path: Path, *, relative_to: Path | None = None) -> Revision | None:
    """Read one revision file, or None if it is not parseable Python."""
    try:
        source = path.read_text(encoding="utf-8")
    except OSError:
        return None
    display = path
    if relative_to is not None:
        with contextlib.suppress(ValueError):
            display = path.relative_to(relative_to)
    try:
        return parse_revision_source(source, path=display.as_posix())
    except SyntaxError:
        return None


def versions_dir(root: Path) -> Path | None:
    """Where the revisions are, honouring `script_location` in `alembic.ini`."""
    location = "migrations"
    ini = root / "alembic.ini"
    if ini.is_file():
        # Interpolation off: alembic.ini legitimately contains `%(here)s`, and
        # ConfigParser raises on it rather than leaving it alone.
        parser = configparser.ConfigParser(interpolation=None)
        try:
            parser.read(ini, encoding="utf-8")
        except (configparser.Error, OSError):
            pass
        else:
            location = parser.get("alembic", "script_location", fallback=location)
    candidate = root / location / "versions"
    return candidate if candidate.is_dir() else None


def order_revisions(revisions: list[Revision]) -> list[Revision]:
    """Dependency order. Filename order is a convention, not a guarantee."""
    known = {revision.revision for revision in revisions}
    children: dict[str | None, list[Revision]] = {}
    for revision in revisions:
        parent = revision.down_revision if revision.down_revision in known else None
        children.setdefault(parent, []).append(revision)

    ordered: list[Revision] = []
    seen: set[int] = set()

    def walk(parent: str | None) -> None:
        for revision in sorted(children.get(parent, []), key=lambda r: (r.revision, r.path)):
            if id(revision) in seen:
                continue
            seen.add(id(revision))
            ordered.append(revision)
            walk(revision.revision)

    walk(None)
    # A branch whose parent file is missing still has to be reported; dropping
    # it silently is how a checker ends up quieter than the tree it reads.
    for revision in revisions:
        if id(revision) not in seen:
            seen.add(id(revision))
            ordered.append(revision)
    return ordered


def load_revisions(root: Path) -> list[Revision]:
    """Every revision under the project's `versions/`, in dependency order."""
    directory = versions_dir(root)
    if directory is None:
        return []
    revisions = []
    for path in sorted(directory.glob("*.py")):
        if path.name == "__init__.py":
            continue
        revision = parse_revision(path, relative_to=root)
        if revision is not None:
            revisions.append(revision)
    return order_revisions(revisions)


# ---------------------------------------------------------------------------
# Findings
# ---------------------------------------------------------------------------


def _literal_bool(text: str | None) -> bool | None:
    if text == "True":
        return True
    if text == "False":
        return False
    return None


def _has_server_default(keywords: Mapping[str, str]) -> bool:
    value = keywords.get("server_default")
    return value is not None and value != "None"


def _is_timestamptz(type_text: str | None) -> bool:
    if not type_text:
        return False
    compact = type_text.lower().replace(" ", "")
    return "timestamptz" in compact or "timezone=true" in compact or "utcdatetime" in compact


def _is_varchar_widening(existing: str | None, new: str) -> bool:
    if existing is None:
        return False
    before, after = _VARCHAR.match(existing), _VARCHAR.match(new)
    if before is None or after is None:
        return False
    if not after.group(1):
        # Bounded to unbounded. No rewrite, no truncation.
        return True
    if not before.group(1):
        return False
    return int(after.group(1)) >= int(before.group(1))


def _sql_timestamptz_without_using(sql: str) -> list[str]:
    """Columns converted to a zone-aware timestamp with no `USING` clause."""
    naked: list[str] = []
    boundaries = [match.start() for match in _SQL_ALTER_COLUMN.finditer(sql)] + [len(sql)]
    for match in _SQL_TO_TIMESTAMPTZ.finditer(sql):
        end = next((start for start in boundaries if start > match.start()), len(sql))
        if not re.search(r"\busing\b", sql[match.end() : end], re.IGNORECASE):
            naked.append(match.group("column").strip('"'))
    return naked


def _nearest_before(pattern: re.Pattern[str], sql: str, position: int, group: str) -> str | None:
    """The last *group* captured before *position*, unquoted.

    `ALTER TABLE t ALTER COLUMN c SET NOT NULL` names its table once and its
    column once, both to the left of the clause carrying the risk. Attributing
    by position keeps each pattern anchored on its own keywords instead of one
    pattern having to span everything in between.
    """
    found: str | None = None
    for match in pattern.finditer(sql):
        if match.start() >= position:
            break
        found = match.group(group)
    return found.strip('"') if found else None


def _copies(sql: str, *, source: str, target: str) -> bool:
    """Whether *sql* moves *source*'s values into *target*.

    `UPDATE t SET target = ... source ...` and `INSERT INTO t (..., target,
    ...) SELECT ... source ...`, and nothing else. This is what suppresses a
    `migration-rename`, so every widening of it silences a finding that was
    correct -- the cost of being narrow is a report, the cost of being loose is
    a column.
    """
    if not source or not target:
        return False
    if not re.search(rf"\b{re.escape(source)}\b", sql, re.IGNORECASE):
        return False
    escaped = re.escape(target)
    flags = re.IGNORECASE | re.DOTALL
    if re.search(_SQL_COPIES_INTO.format(target=escaped), sql, flags):
        return True
    return bool(re.search(_SQL_INSERTS_FROM.format(target=escaped), sql, flags))


def python_remedies(steps: Sequence[str]) -> list[str]:
    """Every backticked span in *steps* that is Python somebody could paste.

    `plan` prints remedies to be copied into a revision, and a remedy that does
    not parse is worse than none because it will be pasted anyway. Telling the
    Python apart from the SQL and the shell in the same sentences is a property
    of the module that writes them, which is why it lives here rather than in
    whatever checks them.
    """
    return [match.group(1) for match in _PYTHON_REMEDY.finditer("\n".join(steps))]


def _risk(
    severity: str,
    code: str,
    message: str,
    why: str,
    *,
    revision: Revision,
    line: int,
    reason: str,
    steps: Sequence[str],
) -> Risk:
    return Risk(
        finding=Finding(
            severity=severity,
            code=code,
            message=message,
            why=why,
            path=revision.path,
            line=line,
        ),
        reason=reason,
        steps=tuple(steps),
    )


def _drop_table_risk(
    revision: Revision, line: int, table: str, rows: RowCounts, *, message: str | None = None
) -> Risk:
    return _risk(
        "critical",
        "migration-drop-table",
        message or f"table {table} is dropped",
        _WHY_DROP_TABLE,
        revision=revision,
        line=line,
        reason=f"{table} is dropped and it {rows.phrase(table)}",
        steps=(
            f"take a dump of {table} and verify it restores",
            "rename the table instead, and drop it a release later",
            "confirm no foreign key still points at it",
        ),
    )


def _drop_column_risk(
    revision: Revision, line: int, table: str, column: str | None, rows: RowCounts
) -> Risk:
    return _risk(
        "high",
        "migration-drop-column",
        f"{table}.{column} is dropped",
        _WHY_DROP_COLUMN,
        revision=revision,
        line=line,
        reason=f"{table}.{column} is dropped and {table} {rows.phrase(table)}",
        steps=(
            "confirm nothing reads the column: `jfast analyze`, then grep",
            "ship the code that stopped using it first, and let it roll out fully",
            "drop the column in a later revision",
        ),
    )


def _index_lock_risk(
    revision: Revision,
    line: int,
    target: str | None,
    table: str,
    rows: RowCounts,
    steps: Sequence[str],
) -> Risk:
    return _risk(
        "medium",
        "migration-index-lock",
        f"index {target} on {table} is built without CONCURRENTLY",
        _WHY_INDEX_LOCK,
        revision=revision,
        line=line,
        reason=f"writes to {table} block while the index builds; {table} {rows.phrase(table)}",
        steps=steps,
    )


def _set_not_null_risk(
    revision: Revision, line: int, table: str, column: str | None, rows: RowCounts
) -> Risk:
    constraint = f"{table}_{column}_not_null"
    return _risk(
        "high",
        "migration-set-not-null",
        f"{table}.{column} becomes NOT NULL",
        _WHY_SET_NOT_NULL,
        revision=revision,
        line=line,
        reason=f"{table}.{column} is validated across the table, which {rows.phrase(table)}",
        steps=(
            f"backfill every NULL in {table}.{column} first, in batches",
            f"`ALTER TABLE {table} ADD CONSTRAINT {constraint} "
            f"CHECK ({column} IS NOT NULL) NOT VALID`",
            f"`ALTER TABLE {table} VALIDATE CONSTRAINT {constraint}`",
            "then SET NOT NULL, which is instant once the constraint is valid",
        ),
    )


def _type_change_risk(
    revision: Revision,
    line: int,
    table: str,
    column: str | None,
    new_type: str,
    rows: RowCounts,
    *,
    explicit_using: bool,
) -> Risk:
    """The rewrite, at the severity the author's own evidence supports.

    A `USING` clause is the author stating the conversion rather than letting
    the implicit cast pick one. The rewrite and its lock are unchanged, so the
    finding stays -- but it drops below the default `--fail-on high`, because
    blocking a deploy on a conversion whose expression is written out is how
    the whole command gets turned off.
    """
    tail = (
        "; the conversion is written out, so this is the lock and nothing else"
        if explicit_using
        else ""
    )
    return _risk(
        "medium" if explicit_using else "high",
        "migration-type-change",
        f"{table}.{column} changes type to {new_type}",
        _WHY_TYPE_CHANGE,
        revision=revision,
        line=line,
        reason=f"{table} is rewritten under ACCESS EXCLUSIVE and it {rows.phrase(table)}{tail}",
        steps=(
            "add a new column of the target type",
            "backfill it in batches, with the application writing both",
            "swap the names in a later revision and drop the old column",
        ),
    )


def _execute_risks(revision: Revision, operation: Operation, rows: RowCounts) -> list[Risk]:
    """What a raw statement does -- for the forms below, and a note when it is not one."""
    sql = operation.sql
    if sql is None:
        return [
            _risk(
                "low",
                "migration-raw-sql",
                "op.execute runs SQL this check could not read",
                (
                    "The statement is assembled at runtime -- an f-string, a variable, a value "
                    "out of settings -- so its text is not in the file. None of the checks below "
                    "ran against it, and a tick on this revision would be claiming they had."
                ),
                revision=revision,
                line=operation.line,
                reason="the statement is built at runtime, so nothing read it",
                steps=(
                    "write it as a literal if it can be one, and run the check again",
                    "otherwise review it by hand: the locks, the row counts and the casts are "
                    "all still yours",
                ),
            )
        ]

    risks: list[Risk] = []
    read = False

    for match in _SQL_DROP_TABLE.finditer(sql):
        read = True
        risks.append(
            _drop_table_risk(revision, operation.line, match.group("table").strip('"'), rows)
        )

    for match in _SQL_TRUNCATE.finditer(sql):
        read = True
        table = match.group("table").strip('"')
        risks.append(
            _drop_table_risk(
                revision,
                operation.line,
                table,
                rows,
                message=f"every row of {table} is deleted",
            )
        )

    for match in _SQL_DROP_COLUMN.finditer(sql):
        read = True
        table = _nearest_before(_SQL_ALTER_TABLE, sql, match.start(), "table")
        if table is None:
            continue
        risks.append(
            _drop_column_risk(
                revision, operation.line, table, match.group("column").strip('"'), rows
            )
        )

    for match in _SQL_SET_NOT_NULL.finditer(sql):
        read = True
        table = _nearest_before(_SQL_ALTER_TABLE, sql, match.start(), "table")
        column = _nearest_before(_SQL_ALTER_COLUMN_NAME, sql, match.start(), "column")
        if table is None:
            continue
        risks.append(_set_not_null_risk(revision, operation.line, table, column, rows))

    for match in _SQL_CREATE_INDEX.finditer(sql):
        read = True
        if match.group("concurrently"):
            continue
        # PostgreSQL lets the name be left out and derives one. The lock is the
        # same either way, so the finding is too.
        named = match.group("name")
        name = named.strip('"') if named else "(unnamed)"
        table = match.group("table").strip('"')
        rewritten = " ".join(
            part for part in ("CREATE INDEX CONCURRENTLY", named, f"ON {table} (...)") if part
        )
        risks.append(
            _index_lock_risk(
                revision,
                operation.line,
                name,
                table,
                rows,
                (
                    f"`{rewritten}`",
                    "run it outside a transaction: CONCURRENTLY cannot run inside one, so the "
                    "revision needs `with op.get_context().autocommit_block(): ...`",
                    "check for an INVALID index afterwards: a concurrent build that fails leaves "
                    "one behind and it has to be dropped by hand",
                ),
            )
        )

    for name in _sql_timestamptz_without_using(sql):
        risks.append(
            _risk(
                "critical",
                "migration-timestamptz-no-using",
                f"{name} becomes timestamptz with no USING clause",
                _WHY_TIMESTAMPTZ,
                revision=revision,
                line=operation.line,
                reason=f"{name} converts through the server's TimeZone",
                steps=(
                    f"append `USING {name} AT TIME ZONE 'UTC'` to the clause",
                    "verify one known row's value before and after, on a server whose TimeZone "
                    "is not UTC",
                ),
            )
        )

    boundaries = [match.start() for match in _SQL_ALTER_COLUMN.finditer(sql)] + [len(sql)]
    for match in _SQL_COLUMN_TYPE.finditer(sql):
        read = True
        table = _nearest_before(_SQL_ALTER_TABLE, sql, match.start(), "table")
        if table is None:
            continue
        end = next((start for start in boundaries if start > match.start()), len(sql))
        risks.append(
            _type_change_risk(
                revision,
                operation.line,
                table,
                match.group("column").strip('"'),
                " ".join(match.group("type").split()),
                rows,
                explicit_using=bool(re.search(r"\busing\b", sql[match.end() : end], re.IGNORECASE)),
            )
        )

    if not read:
        risks.append(
            _risk(
                "low",
                "migration-raw-sql",
                "op.execute runs SQL this check does not read",
                (
                    "Judging arbitrary SQL needs a SQL parser, and a wrong answer about a "
                    "migration is worse than no answer. A named list of statement forms is read "
                    "-- DROP TABLE, TRUNCATE, DROP COLUMN, SET NOT NULL, CREATE INDEX and a "
                    "column type change -- and this statement is not one of them. It has not "
                    "been checked; the tick on this revision would have said it had."
                ),
                revision=revision,
                line=operation.line,
                reason="no check in this command reads this statement",
                steps=(
                    "read it yourself, against the lock and row-count questions the findings "
                    "above ask",
                    "write it as an Alembic operation where one exists -- those are read",
                ),
            )
        )
    return risks


def analyze_revision(revision: Revision, rows: RowCounts) -> list[Risk]:
    """What this revision will do that its author may not have meant, worst first."""
    risks: list[Risk] = []
    created = {op.table for op in revision.operations if op.name == "create_table" and op.table}
    #: Column name and the line it is written on, per table. The line is what
    #: decides whether a backfill sits between an add and a drop.
    added: dict[str, list[tuple[str, int]]] = {}
    dropped: dict[str, list[tuple[str, int]]] = {}
    statements: list[tuple[int, str]] = []

    for operation in revision.operations:
        if operation.name == "execute":
            if operation.sql is not None:
                statements.append((operation.line, operation.sql))
            risks.extend(_execute_risks(revision, operation, rows))
            continue

        table = operation.table
        column = operation.column
        # An operation whose table is not a string literal -- a variable, an
        # f-string. Nothing below can be decided about it, and guessing is what
        # the module docstring rules out.
        if table is None:
            continue

        if operation.name == "add_column":
            added.setdefault(table, []).append((column or "?", operation.line))
            if table in created:
                continue
            nullable = _literal_bool(operation.keywords.get("nullable"))
            if nullable is False and not _has_server_default(operation.keywords):
                risks.append(
                    _risk(
                        "critical",
                        "migration-add-not-null",
                        f"{table}.{column} is NOT NULL with no server_default",
                        (
                            "PostgreSQL rejects `ALTER TABLE ... ADD COLUMN ... NOT NULL` with no "
                            "default the moment the table has a single row, so this passes on an "
                            "empty database and stops the deploy on the one that matters. Add the "
                            "column nullable, backfill it, then set NOT NULL."
                        ),
                        revision=revision,
                        line=operation.line,
                        reason=f"{column} is NOT NULL and {table} {rows.phrase(table)}",
                        steps=(
                            "add the column nullable",
                            "backfill it",
                            "add the NOT NULL constraint",
                            f"`op.alter_column({table!r}, {column!r}, nullable=False)` in a "
                            "follow-up revision, once the backfill has committed",
                        ),
                    )
                )
            continue

        if operation.name == "drop_column":
            dropped.setdefault(table, []).append((column or "?", operation.line))
            risks.append(_drop_column_risk(revision, operation.line, table, column, rows))
            continue

        if operation.name == "drop_table":
            risks.append(_drop_table_risk(revision, operation.line, table, rows))
            continue

        if operation.name == "drop_constraint":
            risks.append(
                _risk(
                    "medium",
                    "migration-drop-constraint",
                    f"constraint {operation.target} is dropped from {table}",
                    (
                        "The guarantee stops holding immediately, and rows that violate it start "
                        "arriving. Putting it back needs a full validating scan of whatever the "
                        "table has become, which is a longer outage than dropping it was."
                    ),
                    revision=revision,
                    line=operation.line,
                    reason=f"{operation.target} stops being enforced on {table}",
                    steps=(
                        "confirm nothing depends on the guarantee, not just on the index",
                        "if it is coming back, re-add it as NOT VALID and VALIDATE separately",
                    ),
                )
            )
            continue

        if operation.name == "create_index" and table not in created:
            if _literal_bool(operation.keywords.get("postgresql_concurrently")) is not True:
                risks.append(
                    _index_lock_risk(
                        revision,
                        operation.line,
                        operation.target,
                        table,
                        rows,
                        (
                            "pass `postgresql_concurrently=True` to op.create_index",
                            "CONCURRENTLY cannot run inside a transaction block, so wrap the "
                            "call: `with op.get_context().autocommit_block(): ...`",
                            "check for an INVALID index afterwards: a concurrent build that "
                            "fails leaves one behind and it has to be dropped by hand",
                        ),
                    )
                )
            continue

        if operation.name == "alter_column" and table not in created:
            keywords = operation.keywords
            new_type = operation.type_text
            explicit_using = "postgresql_using" in keywords
            if new_type and not _is_varchar_widening(keywords.get("existing_type"), new_type):
                if _is_timestamptz(new_type) and not explicit_using:
                    risks.append(
                        _risk(
                            "critical",
                            "migration-timestamptz-no-using",
                            f"{table}.{column} becomes {new_type} with no USING clause",
                            _WHY_TIMESTAMPTZ,
                            revision=revision,
                            line=operation.line,
                            reason=(
                                f"{table}.{column} converts through the server's TimeZone, "
                                f"and {table} {rows.phrase(table)}"
                            ),
                            steps=(
                                f"add `postgresql_using=\"{column} AT TIME ZONE 'UTC'\"` to the "
                                "alter_column call",
                                "or write the ALTER by hand: "
                                f"`ALTER TABLE {table} ALTER COLUMN {column} TYPE timestamptz "
                                f"USING {column} AT TIME ZONE 'UTC'`",
                                "verify one known row's value before and after, on a server "
                                "whose TimeZone is not UTC",
                            ),
                        )
                    )
                risks.append(
                    _type_change_risk(
                        revision,
                        operation.line,
                        table,
                        column,
                        new_type,
                        rows,
                        explicit_using=explicit_using,
                    )
                )
            if _literal_bool(keywords.get("nullable")) is False:
                risks.append(_set_not_null_risk(revision, operation.line, table, column, rows))
            continue

    for table in sorted(added.keys() & dropped.keys()):
        fresh = sorted(name for name, _ in added[table])
        for gone, line in sorted(dropped[table], key=lambda entry: entry[1]):
            if any(
                add_line < copy_line < line and _copies(sql, source=gone, target=target)
                for target, add_line in added[table]
                for copy_line, sql in statements
            ):
                # The values are already in the new column by the time the old
                # one goes. That is a rename, correctly written, and reporting
                # it is the false positive that leaves `--fail-on never` as the
                # only way to run a correct migration through CI.
                continue
            copy_target = fresh[0] if len(fresh) == 1 else "<the new column>"
            risks.append(
                _risk(
                    "critical",
                    "migration-rename",
                    f"{table}.{gone} is dropped in the same revision that adds {', '.join(fresh)}",
                    (
                        "Autogenerate renders a *rename* exactly like this, and the drop takes "
                        "the data with it -- the new column arrives empty. If a rename is what "
                        "was meant, `op.alter_column(..., new_column_name=...)` keeps the "
                        "values; if it was not, the two operations still belong in separate "
                        "revisions."
                    ),
                    revision=revision,
                    line=line,
                    reason=f"{table}.{gone} is dropped and nothing between the two copies it, "
                    f"and {table} {rows.phrase(table)}",
                    steps=(
                        *(
                            f"if {gone} became {name}: "
                            f"`op.alter_column({table!r}, {gone!r}, new_column_name={name!r})`"
                            for name in fresh
                        ),
                        # Advice printed to a reader, never executed: this
                        # module only ever reads revision files. The names come
                        # from the revision's own AST, not from a request.
                        f"if it is a rename this cannot express, copy the values in this same "  # nosec B608
                        f"revision -- `UPDATE {table} SET {copy_target} = {gone}` between the "
                        f"add and the drop -- and this finding goes away",
                        "if it is not a rename, split it into two revisions",
                    ),
                )
            )

    if revision.downgrade_is_empty:
        risks.append(
            _risk(
                "low",
                "migration-no-downgrade",
                "downgrade() is empty",
                (
                    "Not a defect on its own -- plenty of migrations are honestly one-way. It is "
                    "worth knowing before it is applied, because `alembic downgrade -1` will "
                    "report success and change nothing, which is the worst of the three "
                    "possible outcomes."
                ),
                revision=revision,
                line=revision.downgrade_line,
                reason="there is no way back from this revision",
                steps=(
                    "write the downgrade, or",
                    "say in the revision's docstring that it is deliberately one-way, so the "
                    "next reader does not assume otherwise",
                ),
            )
        )

    risks.sort(key=lambda risk: (SEVERITY_ORDER.index(risk.finding.severity), risk.finding.code))
    return risks


# ---------------------------------------------------------------------------
# The database, when there is one
# ---------------------------------------------------------------------------


def resolve_dsn(root: Path, explicit: str | None) -> str | None:
    """The DSN to ask, or None. Never guesses one into existence.

    `DatabaseSettings` has a working default, which is the wrong behaviour
    here: it would turn "no database configured" into "connect to localhost",
    and a failed connection into a finding about the wrong database.
    """
    if explicit:
        return explicit
    from_env = os.environ.get("JFAST_DB_DSN")
    if from_env:
        return from_env
    # A workspace's .env is written for compose -- `<ws>-database:5432` and a
    # `${..._PASSWORD}` only compose fills in -- so read as is it names a host
    # nothing on this machine resolves, the connection fails, and the check
    # falls back to "every table populated" without saying the DSN was the
    # problem. Translated the way `jfast serve`, `worker` and `exec` do it;
    # inside a container, or with no compose file, nothing changes.
    from jfastframework.cli.dev import service_host_environment

    translated = service_host_environment(root).values.get("JFAST_DB_DSN")
    if translated:
        return translated
    dotenv = root / ".env"
    if dotenv.is_file():
        try:
            for raw in dotenv.read_text(encoding="utf-8").splitlines():
                line = raw.strip()
                if line.startswith("JFAST_DB_DSN") and "=" in line:
                    return line.split("=", 1)[1].strip().strip("\"'") or None
        except OSError:
            return None
    return None


async def _read_database(dsn: str, tables: Sequence[str]) -> tuple[str | None, dict[str, int]]:
    from sqlalchemy import text
    from sqlalchemy.engine import make_url
    from sqlalchemy.ext.asyncio import create_async_engine

    url = make_url(dsn)
    if url.get_backend_name() != "postgresql":
        raise RuntimeError(f"{url.get_backend_name()} is not PostgreSQL")
    url = url.set(drivername="postgresql+asyncpg")

    engine = create_async_engine(url, poolclass=None)
    try:
        async with engine.connect() as connection:
            head: str | None = None
            # Asked before it is read: on a database nothing has migrated yet
            # the SELECT fails, and a failed statement aborts the transaction
            # every query below runs in -- so a fresh database was reported as
            # "unavailable" rather than as empty and unmigrated.
            versioned = await connection.execute(
                text("SELECT to_regclass('alembic_version') IS NOT NULL")
            )
            if versioned.scalar():
                with contextlib.suppress(Exception):
                    result = await connection.execute(
                        text("SELECT version_num FROM alembic_version")
                    )
                    row = result.first()
                    head = str(row[0]) if row else None

            present = {
                str(name)
                for (name,) in (
                    await connection.execute(
                        text(
                            "SELECT c.relname FROM pg_class c "
                            "JOIN pg_namespace n ON n.oid = c.relnamespace "
                            "WHERE c.relkind = 'r' "
                            "AND n.nspname NOT IN ('pg_catalog', 'information_schema')"
                        )
                    )
                ).all()
            }
            estimates = {
                str(name): int(count)
                for name, count in (
                    await connection.execute(
                        text(
                            "SELECT c.relname, c.reltuples::bigint FROM pg_class c "
                            "JOIN pg_namespace n ON n.oid = c.relnamespace "
                            "WHERE c.relkind = 'r'"
                        )
                    )
                ).all()
            }

            counts: dict[str, int] = {}
            for table in tables:
                if table not in present:
                    continue
                try:
                    # An identifier cannot be bound as a parameter, so it is
                    # interpolated -- and therefore validated first, the same
                    # way the pgvector store and the PostgreSQL queue do it.
                    quoted = safe_identifier(table, kind="table")
                except ValueError:
                    # PostgreSQL accepts `"my table"` when quoted, and a
                    # read-only diagnostic has no business refusing to run over
                    # one. Unknown is already what this module reports with no
                    # database, and unknown is treated as populated.
                    counts[table] = RowCounts.SOME
                    continue
                # The estimate is stale by design and is -1 on a table that has
                # never been analysed. The EXISTS probe is what makes "empty"
                # mean empty, and it stops at the first row rather than
                # scanning a large table to say something already known.
                # The identifier is validated above; a *value* here would be
                # bound rather than interpolated. On its own line so the waiver
                # sits on the statement bandit reports, not on a continuation.
                probe_sql = f'SELECT EXISTS (SELECT 1 FROM "{quoted}" LIMIT 1)'  # nosec B608
                probe = await connection.execute(text(probe_sql))
                has_rows = bool(probe.scalar())
                estimate = estimates.get(table, 0)
                if not has_rows:
                    counts[table] = 0
                elif estimate > 0:
                    counts[table] = estimate
                else:
                    counts[table] = RowCounts.SOME
            return head, counts
    finally:
        await engine.dispose()


def inspect_database(dsn: str, tables: Sequence[str]) -> tuple[str | None, RowCounts, str | None]:
    """`(applied head, row counts, error)`. An error leaves the counts unknown."""
    try:
        head, counts = asyncio.run(_read_database(dsn, tables))
    except Exception as exc:  # noqa: BLE001 -- every failure means the same thing here
        return None, RowCounts.unknown(), f"{type(exc).__name__}: {exc}"
    return head, RowCounts(known=True, counts=counts), None


def applied_set(revisions: Sequence[Revision], head: str | None) -> frozenset[str]:
    """Every revision at or below *head*, walking the chain backwards."""
    if head is None:
        return frozenset()
    by_id = {revision.revision: revision for revision in revisions}
    applied: set[str] = set()
    cursor: str | None = head
    while cursor is not None and cursor not in applied:
        applied.add(cursor)
        current = by_id.get(cursor)
        cursor = current.down_revision if current else None
    return frozenset(applied)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def severity_counts(risks: Sequence[Risk]) -> dict[str, int]:
    counts = {severity: 0 for severity in SEVERITY_ORDER}
    for risk in risks:
        counts[risk.finding.severity] += 1
    return {severity: count for severity, count in counts.items() if count}


def render_check(reports: Sequence[RevisionReport], *, database: str, scope: str) -> str:
    """One block per revision, findings worst first, in `jfast analyze`'s shape."""
    G = ui.G
    if not reports:
        return f"  {G.tick} no {scope} revisions"

    lines: list[str] = []
    for report in reports:
        header = f"  {report.revision.revision}  {report.revision.path}"
        if not report.risks:
            lines.append(f"{header}  {G.tick}")
            continue
        lines.append(header)
        for risk in report.risks:
            finding = risk.finding
            where = f"line {finding.line}" if finding.line else ""
            lines.append(f"    {finding.severity.upper():<10}{finding.code}  {where}")
            lines.append(f"      {finding.message}")
            lines.append(f"      {finding.why}")
        lines.append("")

    all_risks = [risk for report in reports for risk in report.risks]
    counts = severity_counts(all_risks)
    if counts:
        lines.append("  " + "  ".join(f"{name} {count}" for name, count in counts.items()))
    else:
        lines.append(f"  {G.tick} nothing to report")
    lines.append(f"  database: {database}")
    if database != "connected":
        lines.append("  row counts unknown -- every table is treated as populated")
    return "\n".join(lines)


def render_plan(revision: Revision, risk: Risk | None, *, database: str) -> str:
    """The riskiest thing this revision does, and the safe way to do it."""
    G = ui.G
    if risk is None:
        return (
            f"Migration:  {revision.revision}\n"
            f"File:       {revision.path}\n"
            f"Risk:       none\n\n"
            f"  {G.tick} nothing in this revision needs rewriting"
        )
    lines = [
        f"Migration:  {revision.revision}",
        f"File:       {revision.path}",
        f"Risk:       {risk.finding.severity.upper()}",
        f"Reason:     {risk.reason}",
        f"Database:   {database}",
        "",
        f"  {risk.finding.code}: {risk.finding.message}",
        f"  {risk.finding.why}",
        "",
        "Recommended:",
    ]
    lines.extend(f"  {index}. {step}" for index, step in enumerate(risk.steps, start=1))
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

migration_app = typer.Typer(
    help="Read migrations before they run: what fails, what locks, what is lost.",
    no_args_is_help=True,
)

_LEVELS = (*SEVERITY_ORDER, "never")

PathOption = Annotated[Path, typer.Option("--path", "-p", help="Project root.")]
DsnOption = Annotated[
    str | None,
    typer.Option("--dsn", help="Database to read row counts from. Defaults to JFAST_DB_DSN."),
]
NoDbOption = Annotated[
    bool, typer.Option("--no-db", help="Do not connect. Every table is treated as populated.")
]
JsonOption = Annotated[bool, typer.Option("--json", help="Machine-readable output.")]


def _gather(
    path: Path, dsn: str | None, no_db: bool, every: bool
) -> tuple[list[RevisionReport], str, str, str | None]:
    """`(reports, database, scope, error)` -- the whole of both commands' input."""
    root = path.resolve()
    if versions_dir(root) is None:
        typer.echo(f"no migrations/versions under {root}. Is this a service with a database?")
        raise typer.Exit(Code.CONFIG)

    revisions = load_revisions(root)
    resolved = None if no_db else resolve_dsn(root, dsn)

    rows = RowCounts.unknown()
    database = "skipped" if no_db else "unavailable"
    error: str | None = None
    head: str | None = None
    if resolved is not None:
        tables = sorted({table for revision in revisions for table in revision.tables()})
        head, rows, error = inspect_database(resolved, tables)
        database = "connected" if error is None else "unavailable"

    applied = applied_set(revisions, head)
    scope = "all"
    selected = revisions
    if not every and applied:
        selected = [revision for revision in revisions if revision.revision not in applied]
        scope = "unapplied"

    reports = [
        RevisionReport(revision=revision, risks=tuple(analyze_revision(revision, rows)))
        for revision in selected
    ]
    return reports, database, scope, error


@migration_app.command("check")
def check(
    path: PathOption = Path("."),
    every: Annotated[
        bool, typer.Option("--all", help="Check applied revisions too, not just pending ones.")
    ] = False,
    dsn: DsnOption = None,
    no_db: NoDbOption = False,
    json_out: JsonOption = False,
    fail_on: Annotated[
        str,
        typer.Option(
            "--fail-on",
            help="Exit non-zero at this severity or worse: critical, high, medium, low, never.",
        ),
    ] = "high",
) -> None:
    """What each unapplied revision will do to a database that has data in it.

    Reads `migrations/versions/*.py` with `ast` and never imports them, so it
    works on a project whose dependencies are not installed and on a revision
    that references a model that no longer exists.

    Row counts come from the database when a DSN resolves. When one does not,
    every table is reported as populated rather than assumed empty: a checker
    that goes quiet in the absence of evidence is quiet exactly where it was
    needed.
    """
    if fail_on not in _LEVELS:
        raise typer.BadParameter(f"choose from: {', '.join(_LEVELS)}", param_hint="--fail-on")

    reports, database, scope, error = _gather(path, dsn, no_db, every)
    risks = [risk for report in reports for risk in report.risks]

    payload = {
        "schema_version": SCHEMA_VERSION,
        "ok": not risks,
        "scope": scope,
        "database": database,
        "database_error": error,
        "counts": severity_counts(risks),
        "revisions": [report.describe() for report in reports],
    }
    if json_out:
        typer.echo(jsonlib.dumps(payload, indent=2, default=str))
    else:
        typer.echo(render_check(reports, database=database, scope=scope))

    if fail_on == "never":
        return
    threshold = SEVERITY_ORDER.index(fail_on)
    if any(SEVERITY_ORDER.index(risk.finding.severity) <= threshold for risk in risks):
        raise typer.Exit(Code.MIGRATION)


@migration_app.command("plan")
def plan(
    path: PathOption = Path("."),
    revision_id: Annotated[
        str | None, typer.Option("--revision", "-r", help="Plan this revision instead.")
    ] = None,
    dsn: DsnOption = None,
    no_db: NoDbOption = False,
    json_out: JsonOption = False,
) -> None:
    """The next risky revision, why it is risky, and the safe rewrite.

    Without `--revision` this is the first unapplied revision that carries a
    risk -- the one about to run and do something you did not ask for. The
    `Reason` line states a real row count when a database answered and says so
    when none did; it never reports a table as empty on no evidence.
    """
    reports, database, _, _ = _gather(path, dsn, no_db, every=False)

    if revision_id is not None:
        chosen = next((r for r in reports if r.revision.revision == revision_id), None)
        if chosen is None:
            typer.echo(f"no revision {revision_id!r} among the ones checked.")
            raise typer.Exit(Code.USAGE)
    else:
        chosen = next((report for report in reports if report.risks), None)
        if chosen is None:
            chosen = reports[0] if reports else None

    if chosen is None:
        typer.echo("no revisions to plan.")
        raise typer.Exit(Code.CONFIG)

    worst = chosen.risks[0] if chosen.risks else None
    if json_out:
        typer.echo(
            jsonlib.dumps(
                {
                    "schema_version": SCHEMA_VERSION,
                    "revision": chosen.revision.revision,
                    "path": chosen.revision.path,
                    "database": database,
                    "risk": worst.finding.severity if worst else None,
                    "reason": worst.reason if worst else None,
                    "finding": worst.finding.describe() if worst else None,
                    "steps": list(worst.steps) if worst else [],
                },
                indent=2,
                default=str,
            )
        )
    else:
        typer.echo(render_plan(chosen.revision, worst, database=database))

    if worst is not None and SEVERITY_ORDER.index(worst.finding.severity) <= SEVERITY_ORDER.index(
        "high"
    ):
        raise typer.Exit(Code.MIGRATION)


def register(app: typer.Typer) -> None:
    """Add the `migration` group to *app*. The whole public surface."""
    app.add_typer(migration_app, name="migration")
